// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-tAfFznZqsF3FI7mvdZpYPnaUQ9FAwvU',
    appId: '1:363765096524:web:a82b449856021df6ae94e9',
    messagingSenderId: '363765096524',
    projectId: 'fir-app-cd5f8',
    authDomain: 'fir-app-cd5f8.firebaseapp.com',
    storageBucket: 'fir-app-cd5f8.appspot.com',
    measurementId: 'G-WKHFM7RCPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXs6eKsbus9QzJBVaOQ_l-QEXffoAgSTQ',
    appId: '1:363765096524:android:3242363bd183d21cae94e9',
    messagingSenderId: '363765096524',
    projectId: 'fir-app-cd5f8',
    storageBucket: 'fir-app-cd5f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrSgduo8FEmO8c3CP7v4dcBZh8tY83VGo',
    appId: '1:363765096524:ios:9badb1de13b803cdae94e9',
    messagingSenderId: '363765096524',
    projectId: 'fir-app-cd5f8',
    storageBucket: 'fir-app-cd5f8.appspot.com',
    iosBundleId: 'com.example.firabaseapp',
  );
}
